---
# Source: helm for kubernetes/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-real-6                  # Ingress name
  labels:
    app: nextjs-real-6
spec:
  ingressClassName: nginx   # Optional ingressClass
  rules:
    - host: "nextjs-real-6.smartops.space"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-real-6               # Links to Service name dynamically
                port:
                  number: 3000  # Links to service port dynamically
